version: "3.9"
services:

  station:
    container_name: station
    image: station
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8089:8089"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3307/ski?&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      spring.jpa.hibernate.ddl-auto : update
      spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2



  mysqldb:
    image: "mysql:5.6"
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ski
    ports:
      - "3307:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql


volumes:
  db :
